version: "3.8"

name: backend-delbicos

services:
  postgres:
    image: postgres
    container_name: postgres-delbicos
    environment:
      POSTGRES_DB: delbicos
      POSTGRES_USER: delbicos
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    restart: unless-stopped
  delbicos-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-delbicos
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - MONGODB_URI=${MONGODB_URI:-suaStringConexao}
      - SEQUELIZE_DB_NAME=${SEQUELIZE_DB_NAME:-delbicos}
      - SEQUELIZE_DB_USER=${SEQUELIZE_DB_USER:-delbicos}
      - SEQUELIZE_DB_PASS=${SEQUELIZE_DB_PASS:-postgres123}
      - SEQUELIZE_HOST=${SEQUELIZE_HOST:-postgres}
      - SEQUELIZE_PORT=${SEQUELIZE_PORT:-5432}
      - SEQUELIZE_DIALECT=${SEQUELIZE_DIALECT:-postgres}
      - SECRET_KEY=${SECRET_KEY:-suaChaveSegura}
      - EXPIRES_IN=${EXPIRES_IN:-24h}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-'API_KEY'}
      - SENDER_EMAIL_VERIFICADO=${SENDER_EMAIL_VERIFICADO:-'deliverydebicos@gmail.com'}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped
networks:
  default:
    external: true
    name: delbicos-shared-network
